name: numbers_to_words_russian
description: Numbers to russian words converter. Supports numbers less than a trillion.
version: 1.0.1
homepage: https://github.com/GlebBatykov/numbers_to_words_russian

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
